spring:
  datasource:
    url: jdbc:mysql://**:**/db_fs
    username: ****
    password: ****
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8001
